CREATE TABLE IF NOT EXISTS payment_followups (
  id CHAR(36) PRIMARY KEY,
  payment_id CHAR(36) NOT NULL UNIQUE,
  gym_id VARCHAR(64) NOT NULL,
  paused TINYINT(1) NOT NULL DEFAULT 0,
  auto_reminder TINYINT(1) NOT NULL DEFAULT 0,
  last_reminder_at DATETIME NULL,
  follow_up VARCHAR(20) NOT NULL DEFAULT 'none',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_payment_followups_payment FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE,
  CONSTRAINT fk_payment_followups_gym FOREIGN KEY (gym_id) REFERENCES gyms(id) ON DELETE CASCADE
);